### ISSUE TITLE
Criticisms and concerns on the path of learning paths

### ISSUE THREAD

**Issue by LunaticHacker** [tinkerhub/TinkerHub-Learning-Paths#115]
# Criticisms and concerns on the path of learning paths

In the brief write up i will try to express my concerns of the new "path" learning paths have been taking for a while

I acknowledge the time and effort invested in these new changes, i will try to make this as constructive as possible. I only mean the well-being of the project and the community. Don't take any of these personally.

## Content

Most new creators have shown great understanding of designing a learning paths compared to the initial learning paths, but the concerning issue is that such standards are not maintained for all paths. I will point out some examples to showcase my points, however don't mistake this for an exhaustive list for all the problems

### [The blockchain path](https://github.com/tinkerhub/TinkerHub-Learning-Paths/blob/main/content/blockchain.md)

- The Topics to learn sections is filled with buzzwords from crypto-scammers. For better or worse this doesn't reflect in the resources, 
- I haven't checked all of them but at least some of these resources are paid courses. Although not explicitly stated it's general consensus that these paths should contain free resources accessible to everyone.
- This learning path serves no purpose but to confuse anyone who wants to learn blockchain, if anything the existence of this path should strive to separate blockchain from crypto-scammers not funnel them into it.
- side note: I have seen an Apps section in this path and some others, i don't see any value in it can anyone explain why it exists??

### [The linux path](https://github.com/tinkerhub/TinkerHub-Learning-Paths/blob/main/content/linux.md)

- This learning path just don't make any sense 
- It very boldly claims that it's somehow going to provide a path to learn **Linux**, Linux what? the entire Linux kernal and the ecosystem surrounding it?
- Somehow it ends the topics to learn section with "**freeBSD knowledge**".
- This is a "*learning pit*",the learner is going to fall into this vague topic with no clear path forward,
- Ideally Linux related topics will be in different paths focusing on smaller subsections.

### [Github Actions Path](https://github.com/tinkerhub/TinkerHub-Learning-Paths/blob/main/content/github-actions.md)

- The github actions path have no reason to exist.
- All actions path does is pointing to the documentation, this path have no use just like #111

<br>

There are plenty of other examples, but they all arise from one common issue.

## Code

This project have seen a lot of unnecessary addition to the code in recent days most notably migrating to netlify cms and addition of comments

### NetlifyCMS

Content management systems exist solely for non technical people, i don't understand how this benefits a project like this. Non technical people have no reason to write learning paths. i believe this is the result of a wrong analysis on the stagnation of people writing learning paths in #43.(we will come back to this in the proposed solution)

### Comments
I think this a terrible way to collect feedback ( if that's the intended use-case) for a platform like tinkerhub. Why are we trying to abstract away something simple as opening an issue from CS students who's skill growth is the stated goal of this foundation?.(I'm assuming the rationale of this feature please correct me if I'm wrong)

## Stating Problems and Proposing Solutions

Tinkerhub not only expects beginners to contribute to learning paths(assumption made based on the existence of the CMS and #43 ) it also refuses to review and critique these paths.Learning paths should be created for the beginners not by them(I understand that this might be a contradiction of tinkerhub's learning philosophy). The simple solution to the problems of content without compromising on the core-values of tinkerhub is to add a review system, if resources doesn't allow for per-PR reviews of the content of paths, at least a periodic review that purges unnecessary paths and mistakes will be great.

I prefer the previous system of content management.i will refrain from commenting any further on that. It's better to leave further decisions on them to whoever  introduced those features
 

## Final Notes

- Since I'm not in direct contact with any of the developers, i made a lot of assumptions on the rationale of these changes. if the changes have better intentions let me know.

- I'm writing this in the middle of the night please forgive any typos and grammatical errors 

Thanks for reading :heart:

**Comment by akhilmhdh** [comment]
1. Bad learning paths?

Yes, I would say it's kinda bad compared to the old learning path as it is just a bunch of learning path links. Yes, contents must be added I agree. I just noticed it now. But I won't say it's a bad thing either. For Hugo, I agree, but for blockchain and all, I disagree in two ways. This is not a one-man game or a competition. It's a collaboration. So a person who comes to blockchain sees a lot of links or rather resources. Well, it's a start from my perspective, now next person who feels who can improve it can improve it. 

The resource is a resource. Yes, it's not organized as the previous learning path but still, a start is a start. Now the next person can improve it further. One day that article will be on par like others. But yes, on PR merge this must be considered to add some more content from a textural perspective.

2. Comments

I don't see any issue with that. First TinkerHub and its learning path are not just for CS and these topics can be very broad. It's just a learning path not just CS-based. Kindly understand that TinkerHub is a place for all who love tech and more. Now coming back to the topic. So someone writes a learning path for something else like design and a designer wants to give an update. Which flow would be easier.

3. Netflix CMS

CMS is just a convenience to organize stuff. Is there a rule that technical people cannot organize things? Just kidding. But anyway, it is just for better management that's all. There is a codebase for a static generator in it and also data of all entries. So instead of traversing all these Github URLs, it's much easier to manage it like this. Also live markdown render, filtering, etc. Another point is Netlify cms changes are issued as PR. So there is room for others to review.

**Comment by gautamkrishnar** [comment]
@LunaticHacker Thanks for the detailed feedback. Most of the issues you pointed out related to learning path contents are worth discussing. We can have discussions on the respective issues instead of this one. 

As this is an open-source project anyone can contribute whatever they like it doesn't really matter if the person is a subject matter expert or not. The quality of an open-source project will only improve over time. It can't be done overnight. I am pretty sure that the quality of the paths can be improved by continuous collaboration from the community over time.

We wanted to make this platform accessible to everyone. A person shouldn't be blocked from creating a learning path if he is not familiar with git or Github.  Note that we are not limiting people just to use Netlify CMS. Those who are familiar with Hugo and the command-line interface can still add a new path using the Hugo CLI. We are just providing people a new way of adding content. (We will re-add that in the readme to make it clear to the users.)

`Content management systems exist solely for nontechnical people` -> I personally disagree with this statement. It allows anyone to write a learning path distraction-free and easier without the hurdle of cloning the repo.

We added comments as the method of asking something related to a learning path. Anyone can add comments and ask doubts related to the path. It helps us to create a community discussion centered on paths.

**Comment by LunaticHacker** [comment]
> As this is an open-source project anyone can contribute whatever they like it doesn't really matter if the person is a subject matter expert or not. The quality of an open-source project will only improve over time. It can't be done overnight. I am pretty sure that the quality of the paths can be improved by continuous collaboration from the community over time.

It's true that continuous collaboration will improve learning-paths overtime, but this doesn't mean we have to engage in *anarcho-opensourcism*. All I'm saying is that we need some kind of review when someone submits a learning path as opposed to just blindly merging them. most of the mistakes and  unnecessary paths can be removed in that process itself. Improving the learning path should mean adding better resources, better steps etc, not fixing elementary mistakes and debating the validity of  a path.

As for the CMS, my criticism was from the POV of a non-contributing learner. before the learner and creator was separated by the site and repo, so the new additions felt like bloatware .Upon further consideration of tinkerhub ideals and comments from @akhilmhdh  and @gautamkrishnar  i decided to concede this point.

> We added comments as the method of asking something related to a learning path. Anyone can add comments and ask doubts related to the path. It helps us to create a community discussion centered on paths.

Again, it was a POV issue, didn't want to clutter the site with discussion of creators when they have gh-issues. so for the same reasons as above i concede this point too.

To meet the requirements of non-contributing learners(or maybe it's just me :laughing: ) i will continue to maintain this  [alternative frontend](https://github.com/LunaticHacker/learn) instead.

The main concerns on the content are still unaddressed,content of the learning paths should go through some review, and i don't mean anything extensive, just ensuring that the topic deserves a learning path, stays in the 'path' structure and doesn't include simple mistakes,etc will ensure that "continuous collaboration from the community" will  be productive and useful

**Comment by gautamkrishnar** [comment]
> The main concerns on the content are still unaddressed,content of the learning paths should go through some review, and i don't mean anything extensive, just ensuring that the topic deserves a learning path, stays in the 'path' structure and doesn't include simple mistakes,etc will ensure that "continuous collaboration from the community" will be productive and useful.

Yes, we will definitely improve our review process. We will update the repo settings so that a PR Can be merged only after at least 2 approvals.

> To meet the requirements of non-contributing learners(or maybe it's just me 😆 ) i will continue to maintain this alternative frontend instead.

As an open-source project, you are free to maintain its fork with additional changes. Please make sure that you abide with [LICENCE](https://github.com/tinkerhub/TinkerHub-Learning-Paths/blob/main/LICENSE).

**Comment by LunaticHacker** [comment]
> Yes, we will definitely improve our review process. We will update the repo settings so that a PR Can be merged only after at least 2 approvals

Great, closing this assuming that the consequences of this new rule will be applied retroactively and thus issues of learning paths will be addressed appropriately 👍

**Comment by gautamkrishnar** [comment]
@LunaticHacker thanks for taking your time to discuss the issues. Feel free to contribute to learning paths changes or general improvements back to the repo when you have some time.
